filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.logstash:
  hosts: ["logstash:5000"]

xpack.monitoring.elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]
