---
- name: Deploy Blog Application
  hosts: local
  become: true
  tasks:
    # - name: Install Docker if not present
    #   apt:
    #     name: docker.io
    #     state: latest
    #     update_cache: yes
    #   when: ansible_os_family == "Debian"

    # - name: Install Docker Compose if not present
    #   get_url:
    #     url: "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)"
    #     dest: "/usr/local/bin/docker-compose"
    #     mode: '0755'
    #   when: ansible_os_family == "Debian"

    - name: Pull and Run Docker Compose
      docker_compose:
        project_src: "{{ playbook_dir }}"
        state: present
        pull: yes
        restarted: yes
      become: true
